name: Terraform

on:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_currencyfreaks_api_key: ${{ secrets.CURRENCYFREAKS_API }}
      AWS_REGION: 'us-east-2'
    # services:
    #   localstack:
    #     image: localstack/localstack:latest
    #     ports:
    #       - 4566:4566
    #     env:
    #       SERVICES: s3,ec2,iam,sts,elb,ssm,sqs,ecs,cloudwatch,autoscaling
    #       DEFAULT_REGION: us-east-2
    #       DATA_DIR: /tmp/localstack/data
    #       DEBUG: 1
    #     options: >-
    #       --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - name: Debug AWS secrets
      #   run: |
      #     echo "AWS_ACCESS_KEY_ID is set: ${AWS_ACCESS_KEY_ID:+yes}"
      #     echo "AWS_SECRET_ACCESS_KEY is set: ${AWS_SECRET_ACCESS_KEY:+yes}"

      # - name: Print AWS env (safe)
      #   run: |
      #     if [ -z "$AWS_ACCESS_KEY_ID" ]; then
      #       echo "AWS_ACCESS_KEY_ID is NOT set"
      #     else
      #       echo "AWS_ACCESS_KEY_ID is set"
      #     fi

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl git
      
      # - name: Install AWS CLI
      #   run: |
      #     sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     sudo unzip awscliv2.zip
      #     sudo ./aws/install
      
      - name: Install Terraform

        run: |
          # echo "AWS_ACCESS_KEY_ID is set: ${AWS_ACCESS_KEY_ID:+yes}"
          # echo "AWS_SECRET_ACCESS_KEY is set: ${AWS_SECRET_ACCESS_KEY:+yes}"
          # #sudo aws sts get-caller-identity
          sudo curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o /tmp/terraform.zip \
          && sudo unzip /tmp/terraform.zip -d /tmp \
          && sudo mv /tmp/terraform /usr/local/bin/ \
          && sudo rm -rf /tmp/* \
          && sudo terraform version
        
      - name: Run Terraform

        
        #  AWS_SDK_LOAD_CONFIG: "1"
        #  AWS_ACCESS_KEY_ID: "test"
        #  AWS_SECRET_ACCESS_KEY: "test"
        #  AWS_REGION: "us-east-2"
        #  AWS_ENDPOINT: "http://localhost:4566"
        run: |
          #git clone https://github.com/eitan-93/checkPointHomeAssignment.git 
          #cd checkPointHomeAssignment/infrastructure/terraform
          cd infrastructure/terraform
          terraform init
          terraform fmt
          terraform validate 
          terraform apply -auto-approve
          echo $PWD