name: Terraform

on:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_currencyfreaks_api_key: ${{ secrets.CURRENCYFREAKS_API }}
      AWS_REGION: 'us-east-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl git
      - name: Install Terraform

        run: |

          sudo curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o /tmp/terraform.zip \
          && sudo unzip /tmp/terraform.zip -d /tmp \
          && sudo mv /tmp/terraform /usr/local/bin/ \
          && sudo rm -rf /tmp/* \
          && sudo terraform version
        
      - name: Run Terraform

        run: |

          cd infrastructure/terraform
          terraform init
          terraform fmt
          terraform validate 
          terraform apply -auto-approve
          echo $PWD